# render.yaml
services:
  - type: web
    name: lonng-app
    env: docker
    plan: free
    buildCommand: |
      docker build -t lonng_app -f Dockerfile .
    startCommand: daphne -b 0.0.0.0 -p 8000 myproject.asgi:application
    envVars:
      - key: REDIS_HOST
        value: lonng-redis
      - key: REDIS_PORT
        value: 6379
      # - key: DATABASE_URL
      #   sync: false
      # - key: SECRET_KEY
      #   generateValue: true
    ports:
      - 8000
  - type: redis
    name: lonng-redis
    plan: free