# render.yaml

services:
  - type: web
    name: lonng-app
    env: docker
    plan: free  # or 'starter', 'standard', etc.
    dockerfilePath: ./Dockerfile
    envVars:
      - key: REDIS_HOST
        value: lonng-redis:6379
      - key: REDIS_PORT
        value: 6379
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
    ports:
      - 8000

  - type: redis
    name: lonng-redis
    plan: free  # or 'starter'

