# Generated by Django 5.0.1 on 2025-07-08 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='seen_by',
        ),
    ]
