# Generated by Django 5.0.1 on 2025-09-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_delivary_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(default=0, null=0)),
                ('size', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='addon',
            field=models.ManyToManyField(blank=True, to='shop.addon'),
        ),
    ]
