# Generated by Django 5.0.1 on 2025-09-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_addon_orderitem_addon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
