# Generated by Django 5.0.1 on 2025-07-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_shippingaddress_seen_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(default=0)),
                ('size', models.CharField(max_length=50)),
            ],
        ),
    ]
