# Generated by Django 5.0.1 on 2025-07-09 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_addonproduct_remove_shippingaddress_seen_by'),
        ('shop', '0004_addonproduct'),
    ]

    operations = [
    ]
