# Generated by Django 5.0.1 on 2025-09-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_addon_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='addon',
            field=models.ManyToManyField(blank=True, to='shop.addon'),
        ),
    ]
