# Generated by Django 5.0.1 on 2024-01-21 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_productcategory_product_image_product_product_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='productcategory',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.collectionset'),
        ),
    ]
