# Generated by Django 5.0.1 on 2024-01-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_collectionset_productcategory_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionset',
            name='hero',
            field=models.BooleanField(default=False),
        ),
    ]
