# Generated by Django 5.0.1 on 2024-01-22 06:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ariive_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
