# Generated by Django 5.0.1 on 2024-01-22 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_product_ariive_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ariive_at',
            new_name='arrive_at',
        ),
    ]
