# Generated by Django 5.0.1 on 2024-01-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_product_new_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='collectionset/'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='collection',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='collection',
            field=models.ManyToManyField(to='shop.collectionset'),
        ),
    ]
