# Generated by Django 5.0.1 on 2024-01-23 05:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
