# Generated by Django 5.0.1 on 2024-01-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_shippingaddress_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuppon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuppon_name', models.CharField(max_length=10)),
                ('percent', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
