# Generated by Django 5.0.1 on 2024-01-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_cuppon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_percentange',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
