# Generated by Django 5.0.1 on 2024-02-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_addonproduct_product_add_on_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='add_on_product',
            field=models.ManyToManyField(to='shop.addonproduct'),
        ),
    ]
