# Generated by Django 5.0.1 on 2024-02-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_orderitem_add_on_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonproduct',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
