# Generated by Django 5.0.1 on 2024-02-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_addonproduct_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_on_product2',
            field=models.ManyToManyField(related_name='ad_on_2', to='shop.addonproduct'),
        ),
        migrations.AddField(
            model_name='product',
            name='add_on_product3',
            field=models.ManyToManyField(related_name='ad_on_3', to='shop.addonproduct'),
        ),
    ]
