# Generated by Django 5.0.1 on 2024-02-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='add_on_product',
            field=models.ManyToManyField(blank=True, to='shop.addonproduct'),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_on_product2',
            field=models.ManyToManyField(blank=True, related_name='ad_on_2', to='shop.addonproduct'),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_on_product3',
            field=models.ManyToManyField(blank=True, related_name='ad_on_3', to='shop.addonproduct'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
