# Generated by Django 5.0.1 on 2024-02-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuppon',
            name='min_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
