# Generated by Django 5.0.1 on 2024-02-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_order_totalbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivary_charge',
            field=models.PositiveIntegerField(default=False),
        ),
    ]
