# Generated by Django 5.0.1 on 2024-02-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_order_delivary_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='compressed_image',
            field=models.ImageField(blank=True, null=True, upload_to='review-compressed/'),
        ),
    ]
