# Generated by Django 5.0.1 on 2024-06-24 05:12

import shop.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_review_compressed_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionset',
            name='image',
            field=shop.models.ResizedImageField(blank=True, null=True, upload_to='collectionset/'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=shop.models.ResizedImageField(blank=True, null=True, upload_to='category/'),
        ),
    ]
