# Generated by Django 5.0.1 on 2024-06-24 05:19

import shop.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_alter_collectionset_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='compressed_image',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=shop.models.ResizedImageField(blank=True, null=True, upload_to='product-image/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=shop.models.ResizedImageField(blank=True, null=True, upload_to='product-image/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=shop.models.ResizedImageField(blank=True, null=True, upload_to='product-image/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=shop.models.ResizedImageField(blank=True, null=True, upload_to='product-image/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=shop.models.ResizedImageField(blank=True, null=True, upload_to='product-review/'),
        ),
    ]
