# Generated by Django 5.0.1 on 2024-06-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_remove_review_compressed_image_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ratting',
            field=models.FloatField(default=0),
        ),
    ]
