# Generated by Django 5.0.1 on 2024-06-24 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_product_ratting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ratting',
            new_name='_ratting',
        ),
    ]
