# Generated by Django 5.0.1 on 2024-06-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_rename_ratting_product__ratting'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_stitched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='stitched_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
