# Generated by Django 5.0.1 on 2024-06-25 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0060_orderitem_is_stitched_product_stitched_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stitched_price',
            new_name='unstitched_price',
        ),
    ]
