# Generated by Django 5.0.1 on 2024-06-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0061_rename_stitched_price_product_unstitched_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='is_stitched',
            field=models.BooleanField(default=True),
        ),
    ]
