# Generated by Django 5.0.1 on 2024-07-05 18:53

import shop.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0062_alter_orderitem_is_stitched'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='size_chart',
            field=shop.models.ResizedImageField(blank=True, null=True, upload_to='sizechart/'),
        ),
    ]
