# Generated by Django 5.0.1 on 2024-07-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0063_productcategory_size_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
