# Generated by Django 5.0.1 on 2024-07-14 14:17

import shop.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0064_alter_shippingaddress_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionset',
            name='mobile_image',
            field=shop.models.ResizedImageField(blank=True, null=True, upload_to='collectionset'),
        ),
    ]
