# Generated by Django 5.0.1 on 2024-08-26 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0066_alter_collectionset_mobile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='_ratting',
            new_name='ratting',
        ),
    ]
