# Generated by Django 5.0.1 on 2024-08-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0068_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
