# Generated by Django 5.0.1 on 2024-09-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0070_alter_review_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('view_name', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
