# Generated by Django 5.0.1 on 2024-09-02 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0072_pagevisit_sesson_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagevisit',
            old_name='sesson_address',
            new_name='session_address',
        ),
    ]
