# Generated by Django 5.0.1 on 2024-09-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0073_rename_sesson_address_pagevisit_session_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagevisit',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
