# Generated by Django 5.0.1 on 2024-09-12 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0074_alter_pagevisit_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='size_chart',
        ),
        migrations.AddField(
            model_name='order',
            name='action_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='collectionset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.collectionset'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
