# Generated by Django 5.0.1 on 2024-09-13 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0076_alter_order_action_by_alter_product_collectionset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='action_by',
        ),
    ]
