# Generated by Django 5.0.1 on 2024-11-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0079_product_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='seen_by',
            field=models.ManyToManyField(blank=True, related_name='seen_orders', to='shop.userprofile'),
        ),
    ]
