# Generated by Django 5.0.1 on 2025-01-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0082_alter_shippingaddress_seen_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='collectionset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='collectionset/'),
        ),
        migrations.AlterField(
            model_name='collectionset',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='collectionset/'),
        ),
    ]
