# Generated by Django 5.0.1 on 2025-02-24 07:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0083_product_youtube_video_id_alter_collectionset_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionset',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='collectionset',
            name='mobile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='mobile_image'),
        ),
    ]
