# Generated by Django 5.0.1 on 2025-02-24 08:13

import cloudinary_storage.storage
import shop.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0084_alter_collectionset_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionset',
            name='image',
            field=shop.models.ResizedImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='collectionset/'),
        ),
        migrations.AlterField(
            model_name='collectionset',
            name='mobile_image',
            field=shop.models.ResizedImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='collectionset/'),
        ),
    ]
