# Generated by Django 5.0.1 on 2025-02-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0085_alter_collectionset_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
