# Generated by Django 5.0.1 on 2025-05-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0086_userprofile_is_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionset',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
