# Generated by Django 5.0.1 on 2025-05-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0087_alter_collectionset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='customization_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
