# Generated by Django 5.0.1 on 2025-05-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0088_orderitem_customization_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customization_possible',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
